config_refresh_interval_s: 60
close_position_price_percent: 0.995
open_position_price_percent: 1.02
max_funds_per_trade: 200
max_funds_percentage_per_trade: 0.7
max_leverage: 10
wait_time_after_initial_trade_s: 30
max_hold_position_duration_s: 3600
gain_percentage_to_keep: 0.75
min_percentage_for_the_moon: 1.01
binance_fetcher_refresh_interval_s: 0.2
coin_info_refresh_interval_s: 36000
top_marketcaps_to_skip: 8